name: "Hello world"

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Test Github Action
        uses: Ideaseeker/test-github-action@v1
        with:
          who-to-greet: 'RRRRR'
