name: "Hello world"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - name: My Action
      uses: Ideaseeker/test-github-action@master

#       with:
#         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
#         fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
#     - name: Create local changes
#       run: echo "content" >> "new-file.txt"
#     - name: Commit files
#       run: |
#         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#         git config --local user.name "github-actions[bot]"
#         git add .
#         git commit -m "Update a file"
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: ${{ github.ref }}
