name: "Run testGradleTask"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - name: Run testGradleTask
      run: |
        chmod +x gradlew
        ./gradlew testGradleTask
