name: "Run testGradleTask"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 14
    - name: Chmod gradlew
      run: chmod +x gradlew
    - name: Run testGradleTask
      uses: gradle/gradle-build-action@v2
      with:
        arguments: testGradleTask
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
