name: "Run test-github-action"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 14
    
    - name: Echo FALSE from main
      if: false
      run: echo "FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE"

    - name: Run test-github-action
      uses: Ideaseeker/test-github-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        testsDirectory: .utbit/test
        pushTests: false
