name: "Run test-github-action"

on: [push]
# on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.8

    - name: Run test-github-action
      uses: Ideaseeker/test-github-action@main
#       with:
#         targetClasses: '[com.github.ideaseeker.list.MyLinkedList]'

#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         testsDirectory: .utbit/test
#         pushTests: true
