name: "Run testGradleTask"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 14

    - run: chmod +x gradlew

    - name: Run testGradleTask
      uses: gradle/gradle-build-action@v2
      with:
        arguments: testGradleTask -PtargetClasses="A B" -PtestsDirectory=.utbit/test -PpushTests=false
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit generated tests # only if there are changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A .utbit/test
        git diff --quiet HEAD .utbit/test || git commit -m "[UTBot]: Add generated tests"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: .utbot/utbot.sarif
