name: "Run test-github-action"

# on: [push]
on: pull_request
# on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.8

    - name: Run test-github-action
      uses: Ideaseeker/test-github-action@main
      with:
#         pushTests: 'false'
#         targetClasses: '[com.github.ideaseeker.list.Node]'
#         generatedTestsRelativeRoot: '.utbit/test'
#         testFramework: 'testng'
#         mockFramework: 'mockito'
        generationTimeout: 1000
#         codegenLanguage: 'kotlin'
#         mockStrategy: 'all-except-cut'
#         staticsMocking: 'do-not-mock-statics'
#         forceStaticMocking: 'do-not-force'
#         classesToMockAlways: '[a, b,c,  gg]'
