name: "Upload SARIF"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: CHMOD
      run: chmod +x gradlew

#     - name: Setup Gradle
#       uses: gradle/gradle-build-action@v2
    
#     - name: Execute Gradle build
#       run: ./gradlew build
    
    - name: Execute Gradle myTask
      run: ./gradlew myTask

#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v1
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: utbot.sarif
