name: "Upload SARIF"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8

    - name: CHMOD
      run: chmod +x gradlew
    
    - name: Execute Gradle myTask
      run: ./gradlew myTask

#     - name: Upload SARIF file
#       uses: github/codeql-action/upload-sarif@v1
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: utbot.sarif
